#!/bin/sh

set -e -u -o pipefail

main() {
    if has_src_or_tests_changed; then
        exit_on_lint_error
    fi

    if has_types_changed; then
        update_schemas
    fi
}

exit_on_lint_error() {
    yarn run lint:ci
}

update_schemas() {
    yarn run update-schemas
}

has_src_or_tests_changed() {
    git diff --cached --name-only | \
        grep -q -E "(src/|tests/)"
}

has_types_changed() {
    git diff --cached --name-only | \
        grep -q "src/types.ts"
}

main
