default:
  image: node:14

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG
      when: never

stages:
  - test
  - build
  - release

install_deps:
  stage: .pre
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules
    policy: push
  before_script:
    - node --version
    - yarn --version
  script:
    - yarn install --frozen-lockfile

include:
  - local: '/cicd/gitlab/test.yaml'
  - local: '/cicd/gitlab/build.yaml'
  - local: '/cicd/gitlab/release.yaml'

  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

semgrep-sast:
  cache: {}

secret_detection:
  cache: {}
