/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Year = number;
export type Body = string;
/**
 * Internal codes to distinguish reasons of 404
 */
export type NotFoundCodeEnum = 'NF001' | 'NF002' | 'NF003';

export interface NotFoundModel {
    year: Year;
    body: Body;
    code: NotFoundCodeEnum;
    [k: string]: unknown;
}
